description:
  eng: |
    <p><strong>Korp</strong> is Språkbanken's word research platform.</p>
    <p>
      Search in large amounts of texts, including newspapers, novels and social media.
      The text collections, <em>corpora</em>, are annotated for linguistic features and other attributes.
      Please refer to the <a href="https://spraakbanken.gu.se/en/tools/korp/user-manual" target="_blank">User manual</a> for more information.
    </p>
    <p>
      If you are using Korp in your work, please <a href="https://sprakbanken.se/en/about/how-to-cite#Korp" target="_blank">cite us</a>.
      For questions or comments, contact us at <a href="mailto:info@sprakbanken.se" class="whitespace-nowrap">info@sprakbanken.se</a>.
    </p>
  swe: |
    <p><strong>Korp</strong> är Språkbankens ordforskningsplattform.</p>
    <p>
      Här kan du söka i stora mängder text från bland annat dagstidningar, skönlitteratur och sociala medier.
      Textsamlingarna, <em>korpusarna</em>, är annoterade med språkliga och andra attribut.
      Se gärna <a href="https://spraakbanken.gu.se/verktyg/korp/anvandarhandledning" target="_blank">Användarhandledningen</a> för mer information.
    </p>
    <p>
      Om du använder Korp i ditt arbete ber vi dig <a href="https://sprakbanken.se/om/referera-till-oss#Korp" target="_blank">referera till oss</a>.
      För frågor och kommentarer, kontakta <a href="mailto:info@sprakbanken.se" class="whitespace-nowrap">info@sprakbanken.se</a>.
    </p>

autocomplete: true
map_enabled: false
hits_per_page_values:
  - 25
  - 50
  - 75
  - 100
  - 500
  - 1000

corpus_info_link:
  url_template:
    swe: https://sprakbanken.se/resurser/%s
    eng: https://sprakbanken.se/en/resources/%s
  label:
    swe: Mer information
    eng: More information

enable_backend_kwic_download: false
enable_frontend_kwic_download: true

default_language: swe
languages:
  - value: eng
    label: English
  - value: swe
    label: Svenska

navigation:
  help_links:
    - label:
        swe: Om Korp
        eng: About Korp
      url:
        swe: https://spraakbanken.gu.se/verktyg/korp
        eng: https://spraakbanken.gu.se/en/tools/korp
    - label:
        swe: Användarhandledning
        eng: User manual
      url:
        swe: https://spraakbanken.gu.se/verktyg/korp/anvandarhandledning
        eng: https://spraakbanken.gu.se/en/tools/korp/user-manual
    - label:
        swe: Hur citerar jag Korp?
        eng: How to cite Korp
      url:
        swe: https://sprakbanken.se/om/referera-till-oss#Korp
        eng: https://sprakbanken.se/en/about/how-to-cite#Korp
    - label:
        swe: Korplabb
        eng: Korp Lab
      title:
        swe: Testa nya funktioner i Korplabbet
        eng: Try out new features in the Korp Lab
      url:
        swe: https://spraakbanken.gu.se/korplabb/
        eng: https://spraakbanken.gu.se/korplabb/#?lang=eng
      external: false
      lab: false # A custom field used by plugin code to filter links
    - label:
        swe: Vanliga Korp
        eng: Normal Korp
      title:
        swe: Lämna Korplabbet och gå till standardversionen av Korp
        eng: Leave the Korp Lab and use the official version of Korp
      url:
        swe: https://spraakbanken.gu.se/korp/
        eng: https://spraakbanken.gu.se/korp/#?lang=eng
      external: false
      lab: true # A custom field used by plugin code to filter links
  links: []

frontpage:
  corpus_updates: true

group_statistics:
  - saldo
  - prefix
  - suffix
  - lex
  - lemma
  - sense
  - text_swefn
  - text_blingbring
  - word-prediction--kb-bert
  - e_cat

statistics_search_default: false

# for 'compile statistics by' selector, can be 'union' or 'intersection'
# reduce_word_attribute_selector: intersection
# reduce_struct_attribute_selector: intersection

matomo:
  url: https://spraakbanken.gu.se/stats/
  site: 43
  # Enable real reporting only on live sites
  staging:
    site: 3
  production:
    site: 3

news_url: https://raw.githubusercontent.com/spraakbanken/newsdesk/main/data/korp.yaml

word_picture_tagset:
  # supported pos-tags
  verb: vb
  noun: nn
  adjective: jj
  adverb: ab
  preposition: pp

  # dependency releations
  subject: ss
  object: obj
  adverbial: adv
  preposition_rel: pa
  pre_modifier: at
  post_modifier: et
  adverbial2: aa

word_picture_conf:
  verb:
    - - rel: subject
        color: "#d0d7f0"
      - _
      - rel: object
        color: "#f7d1e4"
      - rel: adverbial
        color: "#edfcd5"
  noun:
    - - rel: preposition_rel
        color: "#fff3d8"
        field_reverse: true
      - rel: pre_modifier
        color: "#caeee8"
      - _
      - rel: post_modifier
        color: "#ffddd8"
    - - _
      - rel: subject
        color: "#d0d7f0"
        field_reverse: true
        alt_label: pos.vb
    - - rel: object
        color: "#f7d1e4"
        field_reverse: true
        alt_label: pos.vb
      - _
  adjective:
    - - _
      - rel: pre_modifier
        color: "#fff3d8"
        field_reverse: true
    - - rel: adverbial2
        color: "#f7d1e4"
      - _
  adverb:
    - - _
      - rel: adverbial
        color: "#fff3d8"
        field_reverse: true
    - - _
      - rel: adverbial2
        color: "#f7d1e4"
        field_reverse: true
  preposition:
    - - _
      - rel: preposition_rel
        color: "#edfcd5"

default_overview_context: 1 sentence
default_reading_context: 1 paragraph

default_within:
  sentence: sentence

default_options:
  is: =
  is_not: "!="
  starts_with: ^=
  contains: _=
  ends_with: "&="
  matches: "*="
  matches_not: "!*="

korp_backend_url: https://ws.spraakbanken.gu.se/ws/korp/v8

map_center:
  lat: 62.99515845212052
  lng: 16.69921875
  zoom: 4

common_struct_types:
  date_interval:
    label:
      eng: time interval
      swe: tidsintervall
    hide_sidebar: "true"
    hide_compare: "true"
    hide_statistics: "true"
    opts: false
    extended_component: dateInterval
